### PR TITLE
Updated and standardized functions 

### PR DESCRIPTION
**Pull request by donbobvanbirt**
Functions have been updated to expect an underscore and be capitalized. However, the old format will still work so these changes should not break existing applications. Any available market provided in the exchange apis should now work, even if we have not yet listed it. One other noticeable change is that incorrect asset pairs will no longer default to 'BTC_USD' but will instead return an error. Empty currency-pair arguments however, will still default to 'BTC_USD'.

### CODE REVIEW

**Comment by passabilities** [comment]
nice I'm glad to see that you used some of my commits from my other pull request

**Comment by passabilities** [comment]
On another project that I'm working on, I hard coded which exchanges expect a "flipped" asset pair so that the project can accept a uniform pair in the form of `BASE_QUOTE` (e.g. `BTC_USD`) and then flip before any fetching is done. Also should note that since Kraken uses real USD and others use USDT they should be treated as different assets especially since Kraken allows `USDT_USD`

**Comment by donbobvanbirt** [comment]
Thanks for your contributions @passabilities!
That is a good point about `USDT`. The goal of this project is to format data from multiple markets into one simple function. Therefore, I thought treating Tether as fiat would be a good idea, but maybe I should reconsider. There is also an issue with exchanges using different codes for some assets (I know this is the case with Dash).
At some point I would also like to create a separate function to receive all available asset pairs by exchange. Unfortunately, I have been very busy writing code for work lately so PRs are always welcome :-)

**Comment by passabilities** [comment]
Yes actually Kraken also uses `XBT` instead of `BTC`. I wish I could make it public but I'm working on a custom API that basically incorporates all other exchange APIs. This is why I added Bittrex before lol 

I really like this project so I will continue to add to as I can

**Pull request merged**
